apiVersion: v1
kind: Service
metadata:
  name: timescaledb-config
  labels:
    app: timescaledb
    component: patroni
spec:
  selector:
    app: timescaledb
  type: ClusterIP
  clusterIP: None
  ports:
  - name: patroni
    port: 8008
    protocol: TCP
