apiVersion: v1
kind: Service
metadata:
  name: timescaledb-replica
  labels:
    app: timescaledb
    component: postgres
    role: replica
spec:
  selector:
    app: timescaledb
    role: replica
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
