# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: timescaledb
  labels:
    app: timescaledb
subjects:
- kind: ServiceAccount
  name: timescaledb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: timescaledb
