apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: timescaledb
  labels:
    app: timescaledb
subjects:
- kind: ServiceAccount
  name: timescaledb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: timescaledb
