apiVersion: v1
kind: Service
metadata:
  name: timescale
  labels:
    app.kubernetes.io/name: timescale
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/name: timescale
