# Why no persistent volume? Because that imposes constraints on the k8s distributions this can be
# deployed on, increases complexity, and may cause costs for users. If you need a pv/pvc, create an
# issue and I'll add an overlay for you, or raise a PR containing an appropriate change/overlay.
resources:
- service.yaml
- deployment.yaml

# This config means whenever MYSQL_SERVICE contains a name matching a Service name (it should,
# always) and the Service name is changed (e.g. with a namePrefix) the MYSQL_SERVICE value should
# be updated correspondingly.
configurations:
- ./kustomizeconfig/namereference.yaml

configMapGenerator:
- name: mysql
  literals:
  - MYSQL_USER=mysql
  - MYSQL_DATABASE=default
  - ALLOW_ROOT_FROM='%'
  - MYSQL_SERVICE=mysql

secretGenerator:
- name: mysql
  literals:
  - MYSQL_PASSWORD=password
  - MYSQL_ROOT_PASSWORD=root
