resources:
- ../base

configMapGenerator:
- name: vault-dev-config
  literals:
  - VAULT_DEV_ROOT_TOKEN_ID=devroottoken
  - VAULT_DEV_LISTEN_ADDRESS=[::]:8200

patches:
- target:
    kind: StatefulSet
    name: vault
  patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: ignored
    spec:
      template:
        spec:
          containers:
          - name: vault
            args:
            - /usr/local/bin/docker-entrypoint.sh vault server -dev -log-level=trace
            envFrom:
            - configMapRef:
                name: vault-dev-config
